# -*- coding: utf-8 -*-
"""Text_Highlighter1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUYip3S485FnPkIRri4zEpkQpuKK-H4i
"""

# Install required libraries
!pip install pymupdf
!pip install transformers

import fitz  # PyMuPDF (for PDFs)
import re  # Regular expressions for whole-word search
from google.colab import files  # For file upload/download
from transformers import pipeline  # Hugging Face LLM

llm_pipeline = pipeline("text-generation", model="facebook/opt-1.3b")

uploaded_files = files.upload()



# Function to highlight exact text in PDFs and display full text
def highlight_text_in_pdfs(pdf_paths, Text):
    """Searches for a long sentence in multiple PDFs, highlights it, and displays the full text of matched PDFs."""

    matched_pdfs = {}

    for pdf_path in pdf_paths:
        doc = fitz.open(pdf_path)
        found = False
        pdf_text = ""  # Store full PDF text

        for page in doc:
            page_text = page.get_text("text")
            pdf_text += page_text + "\n\n"  # Store full text

            # Ensure strict whole-word matching (avoid partial matches)
            search_pattern = r'(?<!\w)' + re.escape(Text) + r'(?!\w)'  # Exact whole word match
            search_pattern = search_pattern.replace(r'\ ', r'\s+')  # Allow spaces & line breaks

            matches = re.finditer(search_pattern, page_text, re.IGNORECASE | re.DOTALL)

            for match in matches:
                rects = page.search_for(match.group(), quads=True)

                for rect in rects:
                    page.add_highlight_annot(rect)
                    found = True

            # Highlight text in extracted output (ANSI Yellow)
            highlighted_text = re.sub(search_pattern, f"\033[43m{Text}\033[0m", pdf_text, flags=re.IGNORECASE | re.DOTALL)

        if found:
            highlighted_pdf = f"highlighted_{pdf_path}"
            doc.save(highlighted_pdf)
            matched_pdfs[highlighted_pdf] = highlighted_text  # Store highlighted text output

    return matched_pdfs



pdf_files = list(uploaded_files.keys())
print(pdf_files)

# Get user input sentence
Text = input("Enter the Text to search and highlight: ").strip()

print(f"\n Searching For: {Text}\n")

# Run highlighting function
highlighted_pdfs = highlight_text_in_pdfs(pdf_files, Text)

# Display and download highlighted PDFs
if highlighted_pdfs:
    print("\n ****************** Matching PDFs with highlighted text: *****************\n")
    for pdf, text in highlighted_pdfs.items():
        print(f"\n******************PDF: {pdf}**********************\n")
        print(text)  # Show highlighted text inside the full PDF text
        # files.download(pdf)
else:
    print("\n No matches found in any PDF.")

